# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step:
        name: Build and test front-end enviroment
        image: node:11
        caches:
          - node
        script:
          - npm install
          - npm run test-vue
    - step:
        name: Build and test back-end enviroment
        image: php:7.2-fpm
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip zip
          - apt-get update && apt-get install -qy git curl libmcrypt-dev mysql-client
          - yes | pecl install mcrypt-1.0.1
          - docker-php-ext-install pdo_mysql
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - ln -f -s .env.pipelines .env
          - php artisan migrate
          - php artisan serve &
          - sleep 5
          - ./vendor/bin/phpunit
        services:
          - mysql

definitions:
  services:
    mysql:
      image: mariadb:10
      environment:
        MYSQL_DATABASE: 'api_test'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'admin'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
