version: "3"

services:
  mysql:
    image: mariadb:10
    container_name: mysql.todo.docker
    stdin_open: true
    tty: true
    networks:
    - global
    env_file:
    - ./docker/mysql/config.env
    volumes:
    - ~/data/mysql.todo.docker:/var/lib/mysql
    restart: always

  php:
    container_name: php.todo.docker
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    networks:
    - global
    stdin_open: true
    tty: true
    env_file:
    - ./.env
    volumes:
    - ./:/opt:cached
    links:
    - mysql
    - mailcatcher
    - redis
    restart: always

  nginx:
    container_name: nginx.todo.docker
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    networks:
    - global
    stdin_open: true
    tty: true
    labels:
      traefik.frontend.rule: "Host:{subdomain}.todo.test,todo.test"
    volumes:
    - ./public:/opt/public:cached
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    links:
    - php
    restart: always

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher.todo.docker
    labels:
      traefik.frontend.rule: "Host:{subdomain}.todo.test,mailcatcher.todo.test"
      traefik.port: "1080"
    networks:
    - global

  redis:
    image: redis:latest
    container_name: redis.todo.docker
    command:
    - "bash"
    - "-c"
    - 'docker-entrypoint.sh --requirepass "$$REDIS_PASSWORD"'
    networks:
    - global
    env_file:
    - ./docker/redis/config.env

networks:
  global:
    external: true
